In [30]:
def zero_mat(n, p):
    Z = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            row.append(0)
        Z.append(row)
    return Z

def deepcopy(A):
    if type(A[0]) == list:
        n = len(A)
        p = len(A[0])
        res = zero_mat(n, p)
        for i in range(0, n):
            for j in range(0, p):
                res[i][j] = A[i][j]
        return res
    
    else:
        n = len(A)
        res = []
        for i in range(0, n):
            res.append(A[i])
        return res
    


def mat_add(A, B):
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] + B[i][j]
            row.append(val)
        res.append(row)
    return res

def mat_sub(A, B):
    n = len(A)
    p = len(A[0])
    
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] - B[i][j]
            row.append(val)
        res.append(row)
    return res

def mat_scal_multi(b, A):
    """
    Multiply scalar and matrix.
    """
    n = len(A)
    p = len(A[0])
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = b * A[i][j]
            row.append(val)
        res.append(row)
    return res

def mat_elem_multi(A, B):
    """
    Multiply two matrix with same size.
    Such as A is 2 x 2, B is 2 x 2.
    """
    n = len(A)
    p = len(A[0])
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            val = A[i][j] * B[i][j]
            row.append(val)
        res.append(row)
    return res

def mat_multi(A, B):
    """
    Multiply two matrix with different size.
    Such as A is 2 x 2, B is 2 x 3
    """
    n = len(A)
    p1 = len(A[0])
    p2 = len(B[0])
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p2):
            val = 0
            for k in range(0, p1):
                val += A[i][k] * B[k][j]
            row.append(val)
        res.append(row)
    return res

def trace(A):
    """
    Get trace of matrix A.
    """
    n = len(A)
    val = 0
    
    for i in range(0, n):
        val += A[i][i]
    return val

def transpose(A):
    """
    Get transpose matrix of matrix A.
    """
    n = len(A)
    p = len(A[0])
    At = []
    
    for i in range(0, p):
        row = []
        for j in range(0, n):
            val = A[j][i]
            row.append(val)
        At.append(row)
    return At

def diag(A):
    """
    Get diagonal matrix of matrix A.
    """
    n = len(A)
    D = []
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(A[i][j])
            
            else:
                row.append(0)
        D.append(row)
    return D

def diag_elem(A):
    """
    Get elements of diagonal matrix.
    """
    n = len(A)
    d = []
    for i in range(0, n):
        d.append(A[i][i])
    return d

def elem_to_diag(a):
    """
    Transfer elements list of diagonal to diagonal matrix.
    """
    n = len(a)
    D = []
    
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i == j:
                row.append(a[i])
            
            else:
                row.append(0)
        D.append(row)
    return D

def identity(n):
    """
    Product identity matrix with size 'n'
    """
    I = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            if i ==j:
                row.append(1)
            else:
                row.append(0)
        I.append(row)
    return I

def u_tri(A):
    """
    Transfor matrix A to upper triangular matrix.
    """
    n = len(A)
    p = len(A[0])
    res = []
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i > j:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

def l_tri(A):
    """
    Transfor matrix A to lower triangular matrix.
    """
    n = len(A)
    p = len(A[0])
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i < j:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

def toeplitz(a, b):
    """
    Transfor to Toeplitz matrix.
    Oftenly be used in timeseries analysis."""
    
    n1 = len(a)
    n2 = len(b)
    A = []
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            if i > j:
                row.append(a[i-j])
            else:
                row.append(b[j-i])
        A.append(row)
    return A

def u_bidiag(A):
    """
    Transfor matrix A to upper bidiagonal matrix
    """
    
    n = len(A)
    p = len(A[0])
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i > j or j-i > 1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

def l_bidiag(A):
    """
    Transfor matrix A to lower bidiagonal matrix.
    """
    
    n = len(A)
    p = len(A[0])
    res = []
    
    for i in range(0, n):
        row = []
        for j in range(0, p):
            if i < j or i - j > 1:
                row.append(0)
            else:
                row.append(A[i][j])
        res.append(row)
    return res

# Householder matrix
def inner_product(a, b):
    """
    Manipulate vector's inner product.
    Input: vector lists, a and b, to inner product
    Output: result of inner product of vector a and vector b.
    """
    n = len(a)
    res = 0
    for i in range(0, n):
        res += a[i] * b[i]
    return res

def outer_product(a, b):
    """
    Manipulate vector's outer product.
    Input: vector list, a and b, to outer product
    Output: result of outer product of vector a and vector b.
    """
    n1 = len(a)
    n2 = len(b)
    res = []
    
    for i in range(0, n1):
        row = []
        for j in range(0, n2):
            val = a[i] * b[i]
            row.append(val)
        res.append(row)
    return res

def householder(v):
    """
    Householder matrix
    Input: list v that manipulate householder matrix.
    Output: householder matrix using list v.
    """
    n = len(v)
    outer_mat = outer_product(v, v)
    inner_val = inner_product(v, v)
    V = []
    for i in range(0, n):
        row = []
        for j in range(0, n):
            val = (2 / inner_val) * outer_mat[i][j]
            row.append(val)
        V.append(row)
    H = mat_sub(identity(n), V)
    return H

In [31]:
A = [[1, 2], [2, 3]]
B = [[2, 3, 4], [3, 4, 5]]
b = 2
mat_add(A, B)
mat_sub(A, B)
mat_scal_multi(2, A)
#mat_elem_multi(A, B)
transpose(B)

C = [[2, 0, 2, 4], [0, 3, 1, 6], [2, 1, 2, 2], [8, 5, 3, 9]]
At = transpose(C)
print(At)
C == At
diag(C)
trace(C)
diag_elem(C)
elem_to_diag(diag_elem(C))
I = identity(b)
mat_multi(A, I)
l_tri(C)

c = [2, 3, 4, 5, 6]
d = [4, 5, 3, 2]
toeplitz(c, d)

u_bidiag(C)
l_bidiag(C)
householder(d)

[[2, 0, 2, 8], [0, 3, 1, 5], [2, 1, 2, 3], [4, 6, 2, 9]]


[[0.40740740740740744,
  -0.5925925925925926,
  -0.5925925925925926,
  -0.5925925925925926],
 [-0.9259259259259258,
  0.07407407407407418,
  -0.9259259259259258,
  -0.9259259259259258],
 [-0.3333333333333333,
  -0.3333333333333333,
  0.6666666666666667,
  -0.3333333333333333],
 [-0.14814814814814814,
  -0.14814814814814814,
  -0.14814814814814814,
  0.8518518518518519]]

**1. Numpy does not provide the function that make 'Toeplitz matrix'.**  

    We need to use 'scipy' library to make toepliz matrix. (<U>scipy.linalg import toeplitz</U>)
    

**2. Numpy does not provide the function that transfor bidiagonal matrix in once.**    

    We need to use other functions to manipulate bidiagonal.  
    Below code is example of manipulating bidiagonal using numpy.
    
**3. Numpy does not provide the function that transfor householder matrix in once.**

    We need to use other fuctions to manipulate householder matrix.
    Example of manipulating housholder matrix is in below.

In [28]:
# Example of manipulating bidiagonal matrix using numpy
import numpy as np
A = np.array([[2, 3, 4, 5], [4, 5, 6, 7], [9, 8, 7, 6], [1, 4, 6, 8]])
print(A)
diag_elem = np.diag(A)
print(diag_elem)
np.diag(diag_elem)

# Upper bidiagonal matrix
u_diag_elem = np.diag(A, k = 1)
print(u_diag_elem)
np.diag(u_diag_elem, k = 1)
u_diag = np.diag(diag_elem) + np.diag(u_diag_elem, k = 1)
print(u_diag)

# Lower bidiagonal matrix
l_diag_elem = np.diag(A, k = -1)
print(l_diag_elem)
np.diag(l_diag_elem, k = -1)
l_diag = np.diag(diag_elem) + np.diag(l_diag_elem, k = -1)
print(l_diag)

[[2 3 4 5]
 [4 5 6 7]
 [9 8 7 6]
 [1 4 6 8]]
[2 5 7 8]
[3 6 6]
[[2 3 0 0]
 [0 5 6 0]
 [0 0 7 6]
 [0 0 0 8]]
[4 8 6]
[[2 0 0 0]
 [4 5 0 0]
 [0 8 7 0]
 [0 0 6 8]]


In [33]:
# Example of manipulating householder matrix using numpy
import numpy as np

v = np.array([3, 7, 9, 0])
n = len(v)
print(n)

outer_mat = np.outer(v, v)
print(outer_mat)

inner_val = np.inner(v, v)
print(inner_val)

I = np.identity(n)
print(I)

H = I - (2 / inner_val) * outer_mat
print(H)

4
[[ 9 21 27  0]
 [21 49 63  0]
 [27 63 81  0]
 [ 0  0  0  0]]
139
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[ 0.8705036  -0.30215827 -0.38848921  0.        ]
 [-0.30215827  0.29496403 -0.90647482  0.        ]
 [-0.38848921 -0.90647482 -0.16546763  0.        ]
 [ 0.          0.          0.          1.        ]]
